# 指定组
archetype.groupId=io.github.taybct
# 指定文件
archetype.artifactId=spring-taybct-cloud-archetype
# 指定版本
archetype.version=3.5.5
# 指定排除的文件
excludePatterns=logs/**,target/**,**/.idea/**,**/*.iml,out/**,temp/**